sidewalk_params:
  my_param: 1000
  spin_freq: 6
  image_topic: /kinect2/qhd/image_color

  edge_side_offset: 50
  edge_marker_width: 6
  edge_points_dist: 10
  edge_start_offset: 35
  edge_side_offset_promile: 10
  detect_percent_of_image: 80

  #define EDGE_MARKER_VERTICAL_POINT_DIST 50

  #define EDGE_START_OFFSET 30
  #define EDGE_END 500