observation_sources: laser_scan_sensor

laser_scan_sensor:
  sensor_frame: laser
  data_type: LaserScan
  topic: /scan_filtered
  marking: true
  clearing: true

point_cloud_sensor:
  sensor_frame: /base_stabilized
  data_type: PointCloud2
  topic: /paw_pointCloud
  marking: true
  clearing: true