global_costmap:
  global_frame: map
  robot_base_frame: base_link
  
  update_frequency: 2.0
  publish_frequency: 5.0
  
  static_map: false
  #rolling_window: true
  transform_tolerance: 1

  width: 30
  height: 30
  origin_x: -15
  origin_y: -15
  resolution: 0.1
