kv01:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  
  joint0_position_controller:
    type: effort_controllers/JointPositionController
    joint: klb0
    pid: {p: 5000.0, i: 10, d: 50, i_clamp: 10}   
  
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: klb1
    pid: {p: 5000.0, i: 10, d: 50, i_clamp: 10}      
  
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: klb2
    pid: {p: 5000.0, i: 10, d: 50, i_clamp: 10}     
  
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: klb3
    pid: {p: 5000.0, i: 10, d: 50, i_clamp: 10}    
  
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: klb4
    pid: {p: 5000.0, i: 10, d: 50, i_clamp: 10}   
    
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: klb5
    pid: {p: 5000.0, i: 10, d: 50, i_clamp: 10}   
